jasp-stats/jaspTTests

- R/ttestindependentsamples.R
counterpart of https://github.com/jasp-stats/jasp-desktop/pull/4069
[diff without whitespace changes](https://github.com/jasp-stats/TTests/pull/3/files?w=1)
> move location of adding levenes footnote

- R/ttestbayesianonesample.R
- tests/testthat/test-ttestbayesianonesample.R
Fix https://github.com/jasp-stats/jasp-issues/issues/1156
> Don't count testValue twice for Wilcoxon

- R/commonbayesianttest.R
- R/ttestpairedsamples.R
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/530
Fixes https://github.com/jasp-stats/jasp-issues/issues/1103
~~Should be reverted by https://github.com/jasp-stats/INTERNAL-jasp/issues/656~~
> Fix dependencies for plots that depend on pairs of variables

- inst/qml/TTestBayesianPairedSamples.qml
- inst/qml/TTestIndependentSamples.qml
- inst/qml/TTestPairedSamples.qml
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1304
> uniform names across Bayesian & Frequentist t-tests

- R/commonbayesianttest.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1222
> Conditionally add a dependency on the variables

- R/commonbayesianttest.R
- R/informedbayesianttestfunctions.R
- R/ttestbayesianindependentsamples.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1513
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1457
> Release fixes 0.15

- inst/qml/TTestIndependentSamples.qml
- inst/qml/TTestOneSample.qml
- inst/qml/TTestPairedSamples.qml
- po/QML-de.po
- po/QML-eo.po
- po/QML-es.po
- po/QML-fr.po
- po/QML-gl.po
- po/QML-id.po
- po/QML-ja.po
- po/QML-nl.po
- po/QML-pt.po
- po/QML-tr.po
- po/QML-zh_Hans.po
- po/QML-zh_Hant.po
As encountered in the teaching stats meeting.
> UI consistency: 'Effect Size' -> 'Effect size'

- R/ttestpairedsamples.R
- tests/testthat/test-ttestpairedsamples.R
- tests/testthat/test-verified-ttestpairedsamples.R
Based on this request: https://forum.cogsci.nl/discussion/7681/z-values-as-output-for-wilcoxon-test-dependent-samples#latest
(and probably not the only one)
> signed rank test - add z-statistic

- R/ttestindependentsamples.R
- tests/testthat/test-ttestindependentsamples.R
Fix https://github.com/jasp-stats/jasp-issues/issues/1641
> Levene uses t and approporiate df

- R/ttestpairedsamples.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2017
> Fix footnote where "effect size" should have been "location parameter"

- R/commonbayesianttest.R
- R/ttestbayesianpairedsamples.R
- R/ttestindependentsamples.R
- R/ttestpairedsamples.R
Hi @boutinb don't forget this:-)
> Add missing translation strings 

- R/ttestbayesianindependentsamples.R
- R/ttestbayesianonesample.R
- R/ttestbayesianpairedsamples.R
- R/ttestindependentsamples.R
- inst/help/TTestIndependentSamples.md
- inst/help/TTestIndependentSamples_nl.md
- inst/qml/TTestOneSample.qml
- po/R-de.po
- po/R-el.po
- po/R-es.po
- po/R-fr.po
- po/R-gl.po
- po/R-id.po
- po/R-ja.po
- po/R-jaspTTests.pot
- po/R-ms.po
- po/R-nl.po
- po/R-pl.po
- po/R-ro.po
- po/R-ru.po
- po/R-tr.po
- po/R-zh_Hans.po
- po/R-zh_Hant.po
Fix https://github.com/jasp-stats/jasp-issues/issues/1735
> Change W to U in Man Whitney test and include some descriptives of ranks

- R/commonbayesianttest.R
- R/ttestindependentsamples.R
- R/ttestonesample.R
- R/ttestpairedsamples.R
- inst/qml/TTestOneSample.qml
- tests/testthat/_snaps/ttestbayesianindependentsamples/descriptives.svg
- tests/testthat/_snaps/ttestbayesianonesample/descriptives.svg
- tests/testthat/_snaps/ttestbayesianpairedsamples/descriptives.svg
- tests/testthat/_snaps/ttestindependentsamples/descriptives.svg
- tests/testthat/_snaps/ttestindependentsamples/mischief-descriptives-plot.svg
- tests/testthat/_snaps/ttestonesample/descriptives.svg
- tests/testthat/_snaps/ttestpairedsamples/descriptives.svg
New version of https://github.com/jasp-stats/jaspTTests/pull/139
> Don's PR for jaspGraphs in T-test

- R/ttestpairedsamples.R
- inst/help/TTestPairedSamples.md
- inst/qml/TTestPairedSamples.qml
- tests/testthat/test-ttestpairedsamples.R
fix https://github.com/jasp-stats/jasp-issues/issues/38, finally!
> Cohen d corrected for correlation in paired samples t-test

- inst/qml/TTestBayesianIndependentSamples.qml
- inst/qml/TTestBayesianOneSample.qml
- inst/qml/TTestBayesianPairedSamples.qml
- inst/qml/TTestIndependentSamples.qml
- inst/qml/TTestOneSample.qml
- inst/qml/TTestPairedSamples.qml
Assumes https://github.com/jasp-stats/jaspTTests/pull/258
@JohnnyDoorn is this more or less what you had in mind?
> Changes for new variablesList/ data reading

- R/ttestindependentsamples.R
- tests/testthat/test-ttestindependentsamples.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/2830
> Compute normality test on the residuals for the independent samples t-test.

- R/ttestpairedsamples.R
Fix small note in https://github.com/jasp-stats/jasp-issues/issues/2127
> update morey correction

- R/commonTTest.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/2939
> fix qq plots

- R/commonbayesianttest.R
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2709
> dependent on "dependent" not on "variables" because the latter does not exist

- R/ttestbayesianindependentsamples.R
- R/ttestbayesianonesample.R
- R/ttestbayesianpairedsamples.R
Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/2821#event-17250011962
> better check on posterior samples wilcoxon tests

- inst/qml/TTestBayesianIndependentSamples.qml
- inst/qml/TTestBayesianOneSample.qml
- inst/qml/TTestBayesianPairedSamples.qml
- inst/qml/TTestIndependentSamples.qml
- inst/qml/TTestOneSample.qml
- inst/qml/TTestPairedSamples.qml
- inst/qml/common/BarPlots.qml
Info fields for the t-tests with updated changes.
> Info fields T-tests(Again)
